### PR TITLE
📁 File: add docker-compose for kafka

### PR DESCRIPTION
**Pull request by kyu1204**
---

<details open="true"><summary>Generated summary (powered by <a href="https://app.graphite.dev">Graphite</a>)</summary>

> #### What Changed
> Added
> - docker-compose.yaml
> #### Testing
> Run the docker-compose.yaml file and verify that Zookeeper, Kafka, and Kafdrop services are up and running on the specified ports.
> #### Reasoning
> Added docker-compose.yaml file to easily deploy and manage the Zookeeper, Kafka, and Kafdrop services using Docker.
</details>

### CODE REVIEW

**Comment by kyu1204** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1** <a href="https://app.graphite.dev/github/pr/mango-api-platform/bifrost/1" target="_blank">Graphite</a> 
    * **PR #2** <a href="https://app.graphite.dev/github/pr/mango-api-platform/bifrost/2" target="_blank">Graphite</a> 
      * **PR #3** <a href="https://app.graphite.dev/github/pr/mango-api-platform/bifrost/3" target="_blank">Graphite</a> 
        * **PR #4** <a href="https://app.graphite.dev/github/pr/mango-api-platform/bifrost/4" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mango-api-platform/bifrost/4?utm_source=stack-comment).

**Review by yourHooni — APPROVED** [review]
수고하셨습니다

**Review by hslim8888 — APPROVED** [review]

**Review by hslim8888 — APPROVED** [review]

**Review by hslim8888 — APPROVED** [review]

**Comment by hslim8888** [comment]
수고하셨습니다.

**Review by hslim8888 — APPROVED** [review]

**Comment by kyu1204** [comment]
### Merge Activity

* **Sep 7, 4:44 AM**: @kyu1204 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/mango-api-platform/bifrost/4).
* **Sep 7, 4:47 AM**: @kyu1204 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/mango-api-platform/bifrost/4).

**Pull request merged**
